# Generated by Django 4.2.2 on 2023-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/img/default-avatar-profile-icon-symbol-for-website-vector-46547084.jpg', null=True, upload_to='user_profiles/'),
        ),
    ]
