# Generated by Django 4.2.2 on 2023-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
