# Generated by Django 4.2.2 on 2023-07-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_upload_image_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='blogs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.blog'),
        ),
    ]
